'use client';

import { useState, useCallback } from 'react';
import QuizFlow from '@/components/planner/QuizFlow';
import MealPlanDisplay from '@/components/planner/MealPlanDisplay';
import AIChatInterface from '@/components/planner/AIChatInterface';
import { compilePrompt, QuizAnswers } from '@/lib/compilePrompt';
import { MealPlanResponse } from '@/lib/types';

/**
 * Medical disclaimer shown at the top of the AI Meal Planner page.
 * Visible without scrolling on initial page load per requirement 5.1.
 */
function MedicalDisclaimer() {
  return (
    <div
      role="alert"
      className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6"
    >
      <div className="flex gap-3">
        <span className="text-amber-600 text-xl flex-shrink-0" aria-hidden="true">
          ⚠️
        </span>
        <div>
          <h3 className="text-sm font-semibold text-amber-800">Important Medical Disclaimer</h3>
          <p className="text-sm text-amber-700 mt-1">
            The meal plans generated by this AI tool are <strong>not medical advice</strong>. They
            are suggestions based on the information you provide. Always consult your doctor or
            registered dietitian before making changes to your diet, especially if you have
            Crohn&apos;s Disease or other medical conditions.
          </p>
        </div>
      </div>
    </div>
  );
}

type PageState = 'quiz' | 'generating' | 'result';

export default function MealPlannerPage() {
  const [pageState, setPageState] = useState<PageState>('quiz');
  const [quizAnswers, setQuizAnswers] = useState<QuizAnswers | null>(null);
  const [mealPlan, setMealPlan] = useState<MealPlanResponse['mealPlan'] | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [compiledPrompt, setCompiledPrompt] = useState<string>('');

  /**
   * Generates a meal plan by POSTing quiz answers to /api/meal-plan.
   * Uses the provided answers or falls back to stored quizAnswers state.
   */
  const generateMealPlan = useCallback(async (answers: QuizAnswers) => {
    setIsLoading(true);
    setError(null);
    setPageState('generating');

    try {
      const response = await fetch('/api/meal-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ quizAnswers: answers }),
      });

      const data: MealPlanResponse = await response.json();

      if (!data.success || !data.mealPlan) {
        const errorMessage =
          data.error || 'We received an unexpected response. Please try again.';
        setError(errorMessage);
        setIsLoading(false);
        setPageState('result');
        return;
      }

      setMealPlan(data.mealPlan);
      setIsLoading(false);
      setPageState('result');
    } catch {
      setError(
        'The AI service is temporarily unavailable. Please try again later.'
      );
      setIsLoading(false);
      setPageState('result');
    }
  }, []);

  /**
   * Handles quiz completion:
   * 1. Stores answers
   * 2. Compiles the prompt for AI chat context
   * 3. Triggers meal plan generation
   */
  const handleQuizComplete = useCallback(
    (answers: Record<string, Record<string, any>>) => {
      const typedAnswers = answers as QuizAnswers;
      setQuizAnswers(typedAnswers);

      // Compile the prompt for later use with AIChatInterface
      const prompt = compilePrompt(typedAnswers);
      setCompiledPrompt(prompt);

      // Trigger generation
      generateMealPlan(typedAnswers);
    },
    [generateMealPlan]
  );

  /**
   * Retries meal plan generation using the stored quiz answers.
   */
  const handleRetry = useCallback(() => {
    if (quizAnswers) {
      generateMealPlan(quizAnswers);
    }
  }, [quizAnswers, generateMealPlan]);

  /**
   * Resets the page back to the quiz state.
   */
  const handleStartOver = useCallback(() => {
    setPageState('quiz');
    setQuizAnswers(null);
    setMealPlan(null);
    setIsLoading(false);
    setError(null);
    setCompiledPrompt('');
  }, []);

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      {/* Page Heading - clearly labeled as AI feature (Requirement 5.2) */}
      <div className="text-center mb-6">
        <h2 className="text-2xl font-bold text-brand-800">
          AI Meal Planner
        </h2>
        <p className="text-sm text-gray-600 mt-1">
          Powered by AI — personalized meal plans for your Crohn&apos;s journey
        </p>
      </div>

      {/* Medical Disclaimer - visible without scrolling (Requirement 5.1) */}
      <MedicalDisclaimer />

      {/* Quiz State */}
      {pageState === 'quiz' && (
        <QuizFlow onComplete={handleQuizComplete} />
      )}

      {/* Generating / Result State */}
      {(pageState === 'generating' || pageState === 'result') && (
        <div className="space-y-6">
          {/* Meal Plan Display — handles loading, error, and success states */}
          <MealPlanDisplay
            mealPlan={mealPlan}
            isLoading={isLoading}
            error={error}
            onRetry={handleRetry}
          />

          {/* AI Chat Interface — shown only after meal plan is successfully generated */}
          {mealPlan && !isLoading && !error && (
            <AIChatInterface currentMealPlan={compiledPrompt} />
          )}

          {/* Start Over Button — allows returning to the quiz */}
          {!isLoading && (
            <div className="text-center pt-4">
              <button
                type="button"
                onClick={handleStartOver}
                className="px-6 py-2 text-sm font-medium text-brand-700 border border-brand-300 rounded-lg hover:bg-brand-50 transition-colors focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
              >
                Start Over
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
