'use client';

import { useState, useCallback, type ReactNode } from 'react';
import QuizFlow from '@/components/planner/QuizFlow';
import MealPlanDisplay from '@/components/planner/MealPlanDisplay';
import AIChatInterface from '@/components/planner/AIChatInterface';
import SavePlanControl from '@/components/planner/SavePlanControl';
import { compilePrompt, compileStoredPlanContext, QuizAnswers } from '@/lib/compilePrompt';
import { MealPlanRecord, MealPlanResponse } from '@/lib/types';

/**
 * Medical disclaimer shown at the top of the AI Meal Planner page.
 * Visible without scrolling on initial page load per requirement 5.1.
 */
function MedicalDisclaimer() {
  return (
    <div
      role="alert"
      className="mb-8 rounded-2xl border border-amber-200 bg-amber-50/80 p-5"
    >
      <div className="flex gap-3">
        <span className="flex h-9 w-9 flex-none items-center justify-center rounded-full bg-amber-100 text-amber-700" aria-hidden="true">
          !
        </span>
        <div>
          <h3 className="mb-1 text-sm font-semibold text-amber-900">Important Medical Disclaimer</h3>
          <p className="text-sm leading-relaxed text-amber-800/80">
        The meal plans generated by this AI tool are <strong>not medical advice</strong>. They
            are suggestions based on the information you provide. Always consult your doctor or
            registered dietitian before making changes to your diet, especially if you have
            Crohn&apos;s Disease or other medical conditions.
          </p>
        </div>
      </div>
    </div>
  );
}

type PageState = 'quiz' | 'generating' | 'result';

export interface MealPlannerPageProps {
  /**
   * The saved-plans panel, rendered above the planner and handed the reopen
   * callback. It is a render prop rather than a direct `SavedPlansList` mount so
   * this page owns the state a reopen changes — the displayed plan, the retained
   * Meal_Plan_Id, and the AI chat context — while the list stays a presentational
   * consumer of it.
   */
  renderSavedPlans?: (openStoredPlan: (record: MealPlanRecord) => void) => ReactNode;
}

export default function MealPlannerPage({ renderSavedPlans }: MealPlannerPageProps = {}) {
  const [pageState, setPageState] = useState<PageState>('quiz');
  const [quizAnswers, setQuizAnswers] = useState<QuizAnswers | null>(null);
  const [mealPlan, setMealPlan] = useState<MealPlanResponse['mealPlan'] | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [compiledPrompt, setCompiledPrompt] = useState<string>('');
  /**
   * The Meal_Plan_Id the displayed plan is stored under, or null when it has
   * never been saved (Requirement 5.13). It lives here rather than inside
   * `SavePlanControl` because it belongs to the plan: it is set by a successful
   * create, carried in by a reopened record, and cleared by anything that puts a
   * different plan on screen.
   */
  const [savedMealPlanId, setSavedMealPlanId] = useState<string | null>(null);

  /**
   * Generates a meal plan by POSTing quiz answers to /api/meal-plan.
   * Uses the provided answers or falls back to stored quizAnswers state.
   */
  const generateMealPlan = useCallback(async (answers: QuizAnswers) => {
    setIsLoading(true);
    setError(null);
    setPageState('generating');
    // A freshly generated plan is a different plan, so it holds no Meal_Plan_Id
    // and its first save creates a record rather than replacing the last one.
    setSavedMealPlanId(null);

    try {
      const response = await fetch('/api/meal-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ quizAnswers: answers }),
      });

      const data: MealPlanResponse = await response.json();

      if (!data.success || !data.mealPlan) {
        const errorMessage =
          data.error || 'We received an unexpected response. Please try again.';
        setError(errorMessage);
        setIsLoading(false);
        setPageState('result');
        return;
      }

      setMealPlan(data.mealPlan);
      setIsLoading(false);
      setPageState('result');
    } catch {
      setError(
        'The AI service is temporarily unavailable. Please try again later.'
      );
      setIsLoading(false);
      setPageState('result');
    }
  }, []);

  /**
   * Handles quiz completion:
   * 1. Stores answers
   * 2. Compiles the prompt for AI chat context
   * 3. Triggers meal plan generation
   */
  const handleQuizComplete = useCallback(
    (answers: Record<string, Record<string, any>>) => {
      const typedAnswers = answers as QuizAnswers;
      setQuizAnswers(typedAnswers);

      // Compile the prompt for later use with AIChatInterface
      const prompt = compilePrompt(typedAnswers);
      setCompiledPrompt(prompt);

      // Trigger generation
      generateMealPlan(typedAnswers);
    },
    [generateMealPlan]
  );

  /**
   * Retries meal plan generation using the stored quiz answers.
   */
  const handleRetry = useCallback(() => {
    if (quizAnswers) {
      generateMealPlan(quizAnswers);
    }
  }, [quizAnswers, generateMealPlan]);

  /**
   * Opens a stored Meal_Plan_Record (Requirements 6.4, 6.7).
   *
   * Three pieces of state move together, and that is the whole point of the
   * handler: the stored content becomes the displayed plan, its Meal_Plan_Id
   * becomes the id a save updates (5.13), and the chat context is recomputed from
   * the stored content so the previously displayed plan stops being supplied to
   * `AIChatInterface` (6.7). The quiz answers behind the old plan are dropped for
   * the same reason — they describe a plan that is no longer on screen.
   */
  const openStoredPlan = useCallback((record: MealPlanRecord) => {
    setQuizAnswers(null);
    setMealPlan(record.content);
    setSavedMealPlanId(record.mealPlanId);
    setCompiledPrompt(compileStoredPlanContext(record.content));
    setIsLoading(false);
    setError(null);
    setPageState('result');
  }, []);

  /**
   * Resets the page back to the quiz state.
   */
  const handleStartOver = useCallback(() => {
    setPageState('quiz');
    setQuizAnswers(null);
    setMealPlan(null);
    setIsLoading(false);
    setError(null);
    setCompiledPrompt('');
    setSavedMealPlanId(null);
  }, []);

  return (
    <div className="page-shell max-w-5xl">
      <div className="page-intro">
        <p className="eyebrow mb-4">Personalized food ideas</p>
        <h2 className="mb-4">
          AI Meal Planner
        </h2>
        <p className="max-w-2xl text-lg leading-relaxed text-brand-800/60">
          Share your preferences and current needs to build a practical meal plan for your
          Crohn&apos;s journey.
        </p>
      </div>

      {/* Medical Disclaimer - visible without scrolling (Requirement 5.1) */}
      <MedicalDisclaimer />

      {/* Saved plans panel, when the caller supplies one (Requirements 6.1, 6.7) */}
      {renderSavedPlans?.(openStoredPlan)}

      {/* Quiz State */}
      {pageState === 'quiz' && (
        <QuizFlow onComplete={handleQuizComplete} />
      )}

      {/* Generating / Result State */}
      {(pageState === 'generating' || pageState === 'result') && (
        <div className="space-y-6">
          {/* Meal Plan Display — handles loading, error, and success states */}
          <MealPlanDisplay
            mealPlan={mealPlan}
            isLoading={isLoading}
            error={error}
            onRetry={handleRetry}
          />

          {/* Save control — inside the displayed plan view (Requirements 5.1, 5.12) */}
          {mealPlan && !isLoading && !error && (
            <SavePlanControl
              mealPlan={mealPlan}
              savedMealPlanId={savedMealPlanId}
              onSaved={setSavedMealPlanId}
            />
          )}

          {/* AI Chat Interface — shown only after meal plan is successfully generated */}
          {mealPlan && !isLoading && !error && (
            <AIChatInterface currentMealPlan={compiledPrompt} />
          )}

          {/* Start Over Button — allows returning to the quiz */}
          {!isLoading && (
            <div className="text-center pt-4">
              <button
                type="button"
                onClick={handleStartOver}
                className="btn-secondary"
              >
                Start Over
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
